# Generated by Django 4.2.7 on 2025-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_way', 'In Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
