# Generated by Django 4.2.7 on 2025-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_lat',
            field=models.FloatField(blank=True, help_text='Customer Latitude', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_lng',
            field=models.FloatField(blank=True, help_text='Customer Longitude', null=True),
        ),
    ]
