# Generated by Django 4.2.7 on 2025-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_lat_order_customer_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatustracking',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
