# Generated by Django 4.2.7 on 2025-12-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='User Message')),
                ('bot_response', models.TextField(verbose_name='Bot Response')),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('intent', models.CharField(blank=True, max_length=50, verbose_name='Intent')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Categories')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-message_time'],
                'indexes': [models.Index(fields=['-message_time'], name='chatbot_cha_message_69153c_idx'), models.Index(fields=['user', '-message_time'], name='chatbot_cha_user_id_8192b6_idx')],
            },
        ),
    ]
