# Generated by Django 4.2.7 on 2025-12-11 10:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Material Name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Arabic Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, verbose_name='Arabic Description')),
                ('default_unit', models.CharField(default='kg', help_text='Common unit: kg, ton, bag, item, cubic meter, etc.', max_length=50, verbose_name='Default Unit')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Material Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='material_listings/%Y/%m/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Image',
                'verbose_name_plural': 'Material Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Listing Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Arabic Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, verbose_name='Arabic Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit', models.CharField(help_text='Unit of measurement (kg, ton, bag, item, cubic meter, etc.)', max_length=50, verbose_name='Unit')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price per Unit')),
                ('minimum_order_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity required for purchase', max_digits=10, null=True, verbose_name='Minimum Order Quantity')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('acceptable', 'Acceptable'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Condition')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('deleted', 'Deleted')], default='draft', max_length=20, verbose_name='Status')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name='Available Until')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Favorites Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Material Listing',
                'verbose_name_plural': 'Material Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('product', 'Product'), ('material', 'Material')], default='product', max_length=20, verbose_name='Order Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default='piece', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='marketplace.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product', verbose_name='Product'),
        ),
        # First add all foreign key fields
        migrations.AddField(
            model_name='materiallisting',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='marketplace.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='materiallisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_listings', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='materialimage',
            name='material_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='marketplace.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='material_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='material_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        migrations.AddField(
            model_name='order',
            name='material_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        migrations.AddField(
            model_name='report',
            name='material_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        migrations.AddField(
            model_name='review',
            name='material_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.materiallisting', verbose_name='Material Listing'),
        ),
        # Now add indexes and constraints after fields exist
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', '-created_at'], name='marketplace_order_t_4351e0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['material_listing'], name='marketplace_materia_06a7be_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['material_listing', '-created_at'], name='marketplace_materia_11b747_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('material_listing__isnull', True), ('product__isnull', False)), models.Q(('material_listing__isnull', False), ('product__isnull', True)), _connector='OR'), name='favorite_either_product_or_material'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_user_product_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('material_listing__isnull', False)), fields=('user', 'material_listing'), name='unique_user_material_favorite'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('material_listing__isnull', True), ('order_type', 'product'), ('product__isnull', False)), models.Q(('material_listing__isnull', False), ('order_type', 'material'), ('product__isnull', True)), _connector='OR'), name='order_type_consistency'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('material_listing__isnull', True), ('product__isnull', False)), models.Q(('material_listing__isnull', False), ('product__isnull', True)), _connector='OR'), name='report_either_product_or_material'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('material_listing__isnull', True), ('product__isnull', False)), models.Q(('material_listing__isnull', False), ('product__isnull', True)), _connector='OR'), name='review_either_product_or_material'),
        ),
        migrations.AddIndex(
            model_name='materiallisting',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__93bb87_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallisting',
            index=models.Index(fields=['material', 'status'], name='marketplace_materia_2c94e3_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallisting',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_57504e_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallisting',
            index=models.Index(fields=['-published_at'], name='marketplace_publish_345c21_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='marketplace_name_61ecab_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category', 'is_active'], name='marketplace_categor_fee7a3_idx'),
        ),
    ]
