# Generated by Django 4.2.7 on 2025-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_default_categories_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('deleted', 'Deleted')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
