# Generated by Django 4.2.7 on 2025-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
