# Generated by Django 4.2.7 on 2025-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notification_order_id_notification_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='material_listing_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
