# Generated by Django 4.2.7 on 2025-12-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_material_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='material_listing_id',
        ),
    ]
