# Generated by Django 4.2.7 on 2025-12-17 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('transport_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle')], max_length=28)),
                ('vehichle_number', models.CharField(blank=True, max_length=50)),
                ('current_lat', models.FloatField(blank=True, help_text='current latitude', null=True)),
                ('current_lng', models.FloatField(blank=True, help_text='current longitude', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_to_destination', models.FloatField(blank=True, help_text='distance in kilometers', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='logistics.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Live Tracking',
                'verbose_name_plural': 'Live Tracking Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourierAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='logistics.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_assignment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Courier Assignment',
                'verbose_name_plural': 'Courier Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['email'], name='logistics_c_email_5ba065_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['is_active'], name='logistics_c_is_acti_279a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['current_lat', 'current_lng'], name='logistics_c_current_c0c785_idx'),
        ),
        migrations.AddIndex(
            model_name='livetracking',
            index=models.Index(fields=['order', '-timestamp'], name='logistics_l_order_i_c8e37b_idx'),
        ),
        migrations.AddIndex(
            model_name='livetracking',
            index=models.Index(fields=['courier', '-timestamp'], name='logistics_l_courier_1e0e78_idx'),
        ),
    ]
