# Generated by Django 4.2.7 on 2025-12-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='vehichle_number',
            new_name='vehicle_number',
        ),
    ]
