# Generated by Django 4.2.7 on 2025-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_token',
            field=models.TextField(blank=True, null=True, verbose_name='push token'),
        ),
    ]
